name: PhoneJobing - Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Login to Railway
#         run: railway run
        run: railway login --browserless
        
      - name: Link Railway
        run: railway link b41397b8-e0d4-4782-98fe-c44735b5ac4b
        
      - name: Deploy Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
